alias eclipse_catkin='catkin build -G"Eclipse CDT4 - Unix Makefiles" -DCMAKE_BUILD_TYPE=Release'
alias vscode='code --proxy-server=http://127.0.0.1:3128'

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
