name:               lan-explorer
version:            '0.0.1'
summary:            lan_explorer
description:        |
  lan_explorer

grade:              stable
confinement:        devmode
icon:               snap/gui/icon.png
type:               app


apps:
  lan-explorer:
    command:        desktop-launch ${SNAP}/bin/lan_explorer
    plugs:          [home, unity7, x11, camera,network-bind, network-control, account-control]


parts:
  lan-explorer:
    source: .
    plugin: cmake
    configflags:
      - -DCREATE_SNAP_APP=ON
    after:          [desktop-gtk3]
    # A list of Ubuntu packages to be installed on the host to aid in building the part. These packages will not go into the final snap.
    build-packages:
      - cmake
      - build-essential
      - libgtkmm-3.0-dev
  desktop-gtk3:
      # A set of Ubuntu packages to be downloaded and unpacked to join the part before it’s built. Note that these packages are not installed on the host. Like the rest of the part, all files from these packages will make it into the final snap unless filtered out via the prime keyword.
    stage-packages:
      - light-themes
      - libc6
      - libstdc++6



  #   build-packages:
  #     - build-essential
  #     - qt5-default
  #     - qtbase5-dev
  #     - libstdc++6
  #     - libopencv-dev
  #     - libopencv-calib3d-dev
  # desktop-qt5:
  #   # A set of Ubuntu packages to be downloaded and unpacked to join the part before it’s built. Note that these packages are not installed on the host. Like the rest of the part, all files from these packages will make it into the final snap unless filtered out via the prime keyword.
  #   stage-packages:
  #     - libtiff5-dev
  #     - libjpeg8-dev
  #     - libxkbcommon0
  #     - ttf-ubuntu-font-family
  #     - dmz-cursor-theme
  #     - light-themes
  #     - shared-mime-info
  #     - libqt5gui5
  #     - libgdk-pixbuf2.0-0
  #     - libqt5svg5 # for loading icon themes which are svg
  #     - locales-all
